apiVersion: apps/v1
kind: Deployment
metadata:
   name: mlflowserver
   namespace: mlflow
spec:
   selector:
      matchLabels:
         app: mlflowserver
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: mlflowserver
      spec:
         containers:
         - name: mlflowserver
           image: mlflow_server:latest
           ports:
           - containerPort: 5002
             name: mlflowserver
           imagePullPolicy: Never
           args: ["--local"]
           volumeMounts:
           - name: mlflow-storage
             mountPath: /mnt/mlflow
         volumes:
         - name: mlflow-storage
           persistentVolumeClaim:
             claimName: mlflow-pvc
