apiVersion: v1
kind: Service
metadata:
   name: mlflowserver
   namespace: mlflow
spec:
   type: NodePort
   ports:
   -  port: 5002
      protocol: TCP
      targetPort: 5002
      name: http
   selector:
      app: mlflowserver
