apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
  namespace: mysqldb
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
